INSERT INTO "public"."smart_contracts" ("name",
                                        "compiler_version",
                                        "optimization",
                                        "contract_source_code",
                                        "abi",
                                        "address_hash",
                                        "inserted_at",
                                        "updated_at",
                                        "constructor_arguments",
                                        "optimization_runs",
                                        "evm_version",
                                        "external_libraries",
                                        "verified_via_sourcify",
                                        "is_vyper_contract",
                                        "partially_verified",
                                        "file_path",
                                        "is_changed_bytecode",
                                        "bytecode_checked_at",
                                        "contract_code_md5",
                                        "compiler_settings",
                                        "verified_via_eth_bytecode_db",
                                        "license_type",
                                        "verified_via_verifier_alliance",
                                        "certified",
                                        "is_blueprint")
VALUES ('GovHub',
        'v0.8.22+commit.4fc1097e',
        't',
        '',
        '[{"anonymous":false,"inputs":[{"indexed":false,"internalType":"bytes","name":"message","type":"bytes"}],"name":"failReasonWithBytes","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"message","type":"string"}],"name":"failReasonWithStr","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"key","type":"string"},{"indexed":false,"internalType":"bytes","name":"value","type":"bytes"}],"name":"paramChange","type":"event"},{"inputs":[],"name":"CODE_OK","outputs":[{"internalType":"uint32","name":"","type":"uint32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"CROSS_CHAIN_CONTRACT_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"ERROR_TARGET_CONTRACT_FAIL","outputs":[{"internalType":"uint32","name":"","type":"uint32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"ERROR_TARGET_NOT_CONTRACT","outputs":[{"internalType":"uint32","name":"","type":"uint32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"GOVERNOR_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"GOV_HUB_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"GOV_TOKEN_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"INCENTIVIZE_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"LIGHT_CLIENT_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"RELAYERHUB_CONTRACT_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"SLASH_CONTRACT_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"STAKE_CREDIT_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"STAKE_HUB_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"STAKING_CONTRACT_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"SYSTEM_REWARD_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"TIMELOCK_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"TOKEN_HUB_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"TOKEN_MANAGER_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"TOKEN_RECOVER_PORTAL_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"VALIDATOR_CONTRACT_ADDR","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"alreadyInit","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"botChainID","outputs":[{"internalType":"uint16","name":"","type":"uint16"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint8","name":"","type":"uint8"},{"internalType":"bytes","name":"","type":"bytes"}],"name":"handleAckPackage","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint8","name":"","type":"uint8"},{"internalType":"bytes","name":"","type":"bytes"}],"name":"handleFailAckPackage","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint8","name":"","type":"uint8"},{"internalType":"bytes","name":"msgBytes","type":"bytes"}],"name":"handleSynPackage","outputs":[{"internalType":"bytes","name":"responsePayload","type":"bytes"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"key","type":"string"},{"internalType":"bytes","name":"value","type":"bytes"},{"internalType":"address","name":"target","type":"address"}],"name":"updateParam","outputs":[],"stateMutability":"nonpayable","type":"function"}]',
        decode('0000000000000000000000000000000000001007', 'hex'),
        '2026-02-16 09:47:27.157115',
        '2026-02-16 10:19:31.858411',
        '',
        NULL,
        'paris',
        '{}',
        'f',
        'f',
        'f',
        'contracts/GovHub.sol',
        'f',
        '2026-02-16 10:01:55.450378',
        '2ba0ca7dadd09e51ed2376922364ca74',
        '{"libraries": {}, "optimizer": {"runs": 200, "enabled": false}, "evmVersion": "paris", "outputSelection": {"*": {"": ["*"], "*": ["*"]}}}',
        'f',
        3,
        'f',
        NULL,
        'f');


INSERT INTO "public"."address_names" (
    "address_hash",
    "name",
    "primary",
    "inserted_at",
    "updated_at",
    "metadata"
)
VALUES
    (
        decode( '0000000000000000000000000000000000001007', 'hex' ),
        'GovHub',
        't',
        '2026-01-17 08:59:19.795661',
        '2026-01-17 08:59:19.795661',
        NULL
    );